import { Router } from 'express';
import { generatePet, generateUser } from '../utils/mocking.js';
import userModel from '../dao/models/User.js';
import petModel from '../dao/models/Pet.js';

const router = Router();

router.get('/mockingpets', (req, res) => {
    const pets= [];

    for (let i = 0; i<100; i++) {
        pets.push(generatePet());
    }

    req.logger.info("100 pets generated by Mocking");
    res.send({ status: 'success', payload: pets });
});

router.get('/mockingusers', async (req, res) => {
    const users= [];

    for (let i = 0; i<50; i++) {
        users.push(await generateUser());
    }

    req.logger.info("50 users generated by Mocking");
    res.send({ status: 'success', payload: users });
});

router.post('/generateData', async (req, res) => {
    try {
        const { users = 0, pets = 0 } = req.body;
        const newUsers = [];
        const newPets = [];

        for (let i = 0; i < users; i++) {
            newUsers.push(await generateUser());
        }

        for (let i = 0; i < pets; i++) {
            newPets.push(generatePet());
        }

        let insertedUsers = [];
        let insertedPets = [];

        if (newUsers.length > 0) {
            insertedUsers = await userModel.insertMany(newUsers);
            req.logger.info(`Se insertaron ${insertedUsers.length} usuarios en la BD`);
        }

        if (newPets.length > 0) {
            insertedPets = await petModel.insertMany(newPets);
            req.logger.info(`Se insertaron ${insertedPets.length} mascotas en la BD`);
        }

        res.send({ 
            status: 'success', 
            message: 'Datos generados e insertados correctamente',
            payload: {
                usersInserted: insertedUsers.length,
                petsInserted: insertedPets.length
            }
        });

    } catch (error) {
        req.logger.error(`Error al insertar datos de prueba: ${error.message}`);
        res.status(500).send({ status: 'error', error: 'Error interno al insertar los datos' });   
    }

})


export default router;